import Link from 'next/link';
import Script from 'next/script';
import AdPlaceholder from '@/components/ui/AdPlaceholder';
import { buildMetadata } from '@/lib/seo';

export const metadata = buildMetadata({
  title: 'PRC Oath Taking Guide 2026 - Schedule, Requirements & Process',
  description:
    'Complete PRC oath taking guide 2026. How to register for your oath on LERIS, what to bring, online vs face-to-face ceremony, what happens if you miss the mass oath, and what comes after.',
  path: '/blog/prc-oath-taking-guide',
});

const SCHEMA_HOWTO = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Complete Your PRC Oath Taking',
  description:
    'Step-by-step guide to registering for and attending your PRC professional oath taking, online or face-to-face.',
  step: [
    { '@type': 'HowToStep', name: 'Register on LERIS', text: 'Log in at online.prc.gov.ph, select Oath transaction, enter your Application Number, and book your slot.' },
    { '@type': 'HowToStep', name: 'Print Your Oath Form', text: 'Print the Oath Form with your personal QR code generated by LERIS.' },
    { '@type': 'HowToStep', name: 'Attend the Ceremony', text: 'Attend face-to-face in formal attire with your Oath Form and valid ID, or join online with camera on using your registered name.' },
    { '@type': 'HowToStep', name: 'Proceed to Initial Registration', text: 'After your attendance is recorded, book your Initial Registration appointment on LERIS to get your PRC ID.' },
  ],
  author: { '@type': 'Organization', name: 'LisensyaPrep Team' },
  publisher: { '@type': 'Organization', name: 'LisensyaPrep' },
  datePublished: '2026-07-10',
};

const SCHEMA_FAQ = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'Is oath taking required before getting my PRC ID?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes. The professional oath is a legal prerequisite, and initial registration cannot be completed without recorded oath attendance.',
      },
    },
    {
      '@type': 'Question',
      name: 'What do I need for online oath taking?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Any device with an internet connection and a camera, your printed Oath Form with QR code, a valid ID ready for verification, and your registered name as your display name. Formal attire applies even at home.',
      },
    },
    {
      '@type': 'Question',
      name: 'What happens if I miss the mass oath taking?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'You can request a special or individual oath-taking from your Professional Regulatory Board citing your reason, join an online ceremony if available, or attend the next scheduled batch.',
      },
    },
  ],
};

const RELATED_PRC_ARTICLES = [
  { text: 'What to Do After Passing the Board Exam Philippines', href: '/blog/after-passing-board-exam-philippines' },
  { text: 'PRC Initial Registration 2026: How to Get Your PRC ID', href: '/blog/prc-initial-registration-guide' },
  { text: 'LERIS PRC Online Guide 2026', href: '/blog/leris-prc-online-guide' },
  { text: 'PRC ID Renewal and CPD Guide', href: '/blog/prc-id-renewal-cpd-guide' },
];

function formatInline(text) {
  return text
    .replace(
      /\[([^\]]+)\]\((https?:\/\/[^)]+|\/[^)]*)\)/g,
      (_, t, url) =>
        `<a href="${url}"${url.startsWith('http') ? ' target="_blank" rel="noopener noreferrer"' : ''} class="text-yellow-400 hover:text-yellow-300 underline underline-offset-2">${t}</a>`
    )
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-white font-semibold">$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em class="text-gray-400 italic">$1</em>')
    .replace(/`(.+?)`/g, '<code class="bg-white/10 px-1 rounded text-yellow-300 text-xs">$1</code>');
}

// Markdown-like renderer: headings, rules, bullet/numbered lists, tables, and paragraphs.
function renderContent(content) {
  const lines = content.trim().split('\n');
  const elements = [];
  let key = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (line.startsWith('## ')) {
      elements.push(<h2 key={key++} className="text-2xl font-extrabold text-white mt-8 mb-4">{line.slice(3)}</h2>);
    } else if (line.startsWith('### ')) {
      elements.push(<h3 key={key++} className="text-lg font-bold text-yellow-400 mt-6 mb-3">{line.slice(4)}</h3>);
    } else if (line.trim() === '---') {
      elements.push(<hr key={key++} className="border-white/10 my-6" />);
    } else if (line.startsWith('| ') && line.endsWith(' |')) {
      if (line.match(/^\|[-\s|]+\|$/)) continue; // separator row
      const cells = line.split('|').slice(1, -1).map((c) => c.trim());
      const isHeader = lines[i + 1]?.includes('---') && lines[i + 1]?.match(/^\|[-\s|]+\|$/);
      if (isHeader) {
        elements.push(
          <tr key={key++} className="border-b border-white/10">
            {cells.map((cell, ci) => (
              <th key={ci} className="px-4 py-2 text-left text-yellow-400 font-semibold text-sm">{cell}</th>
            ))}
          </tr>
        );
      } else {
        elements.push(
          <tr key={key++} className="border-b border-white/5">
            {cells.map((cell, ci) => (
              <td key={ci} className="px-4 py-2 text-gray-300 text-sm" dangerouslySetInnerHTML={{ __html: formatInline(cell) }} />
            ))}
          </tr>
        );
      }
    } else if (line.startsWith('- ')) {
      elements.push(<li key={key++} dangerouslySetInnerHTML={{ __html: formatInline(line.slice(2)) }} />);
    } else if (line.match(/^\d+\. /)) {
      elements.push(<li key={key++} dangerouslySetInnerHTML={{ __html: formatInline(line.replace(/^\d+\. /, '')) }} />);
    } else if (line.trim() === '') {
      elements.push(<div key={key++} className="h-2" />);
    } else {
      elements.push(<p key={key++} className="text-gray-300 text-sm my-2 leading-relaxed" dangerouslySetInnerHTML={{ __html: formatInline(line) }} />);
    }
  }

  // Wrap consecutive <li> into <ul> and consecutive <tr> into <table>.
  const wrapped = [];
  let listBuffer = [];
  let tableBuffer = [];
  const flushList = () => {
    if (listBuffer.length) {
      wrapped.push(<ul key={`ul-${key++}`} className="list-disc list-inside space-y-1 my-3 text-gray-300 text-sm pl-2">{listBuffer}</ul>);
      listBuffer = [];
    }
  };
  const flushTable = () => {
    if (tableBuffer.length) {
      wrapped.push(
        <div key={`table-${key++}`} className="overflow-x-auto my-4">
          <table className="w-full bg-[#0a1022] border border-white/10 rounded-xl overflow-hidden">
            <tbody>{tableBuffer}</tbody>
          </table>
        </div>
      );
      tableBuffer = [];
    }
  };
  for (const el of elements) {
    if (el.type === 'li') {
      flushTable();
      listBuffer.push(el);
    } else if (el.type === 'tr') {
      flushList();
      tableBuffer.push(el);
    } else {
      flushList();
      flushTable();
      wrapped.push(el);
    }
  }
  flushList();
  flushTable();
  return wrapped;
}

const MAIN_CONTENT = `
Passing the board exam makes you a passer. Taking your **professional oath** is what starts making you a professional. It is a legal requirement — you cannot complete your initial registration or claim your PRC ID without it — and it is also a milestone ceremony you will remember for the rest of your career.

I am a Registered Pharmacist, and I took my own oath online from home during the pandemic. All I really needed was a device that could connect to the internet with a working camera — and, yes, formal attire, even at home. These days the process has evolved, so this guide covers both the current face-to-face ceremonies and the online option, step by step.

**Quick answer:** Register for an oath slot on LERIS (online.prc.gov.ph) → print your Oath Form with QR code → attend the ceremony (face-to-face or online) → your attendance is recorded → proceed to Initial Registration for your PRC ID.

---

## When Is the Oath Taking?

Oath-taking schedules are announced by the PRC and your Professional Regulatory Board **shortly after board exam results are released** — often within a few weeks. Schedules vary by profession and region.

Where to watch for announcements:
- The official **PRC website (prc.gov.ph)**
- The **PRC official Facebook page** and your regional PRC office's page
- Your **LERIS account**, where available oath slots appear under the Oath transaction

---

## Step 1: Register for Your Oath Slot on LERIS

The oath now comes **before** initial registration in the current PRC flow, and everything starts online:

1. Log in at **online.prc.gov.ph** (same account you used for your exam application)
2. Click **Select Transaction → Oath**
3. Choose the ceremony type available for your profession
4. Select your profession and enter your **Application Number** (from your Notice of Admission)
5. The system automatically verifies that you passed — only successful examinees can proceed
6. Choose your preferred PRC regional office and available date

**Tip:** Register in the same region where you took your exam and plan to complete your registration. It keeps all your records in one office and avoids cross-region delays.

New to LERIS? Full portal walkthrough here: [LERIS PRC Online Guide](/blog/leris-prc-online-guide)

## Step 2: Print Your Oath Form (Do Not Skip This)

After booking, LERIS generates your **Oath Form with a personal QR code**. Print it and keep it safe.

This QR code is scanned at the ceremony to officially tag you as "attended." No scanned QR, no recorded attendance — and your initial registration cannot proceed without it.

## Step 3: Attend the Ceremony

### Face-to-Face Mass Oath Taking (the norm in 2026)

What to bring:
- Printed **Oath Form with QR code**
- **Valid government ID**
- Your **Notice of Admission** (for identification, just in case)

What to wear: **formal attire.** This is an official ceremony — business attire or your profession's recognized formal wear. Many professions hold large venue ceremonies where you take the oath together with hundreds of fellow passers, sometimes with an induction from your professional organization.

The ceremony itself typically runs a few hours including registration, the oath proper, and closing. Arrive early — lines for QR scanning get long.

### Online Oath Taking

When I took my oath online in 2022, the requirements were refreshingly simple: any device that can connect to the internet and has a camera. That is genuinely all the technology you need. A few things from my experience:

- **Camera must stay on** during the ceremony — this is how attendance is monitored
- **Use your registered full name** as your display name so you can be identified
- **Have your valid ID ready** in case verification is required
- **Dress formally even at home.** I did, and I am glad I did — there are screenshots of that ceremony I would not want to explain otherwise

And here is the part people always ask: after my online oath, I did not have to submit anything to prove attendance. It was recorded automatically through the session. Once done, I simply proceeded to book my initial registration.

## Step 4: What Happens After the Oath

Your attendance is recorded in the PRC system. From here:

1. Return to LERIS → **Select Transaction → Initial Registration**
2. Book your appointment, pay the fees (₱1,050 total), and claim your PRC ID

Complete walkthrough with my own experience: [PRC Initial Registration 2026: How to Get Your PRC ID](/blog/prc-initial-registration-guide)

---

## What If You Miss the Mass Oath Taking?

Life happens — work, distance, emergencies. Missing the mass ceremony does not forfeit your license. Your options:

1. **Special or individual oath-taking** — request one from your Professional Regulatory Board through the PRC, citing your reason
2. **Online oath-taking** — where available for your profession
3. **Join the next scheduled ceremony** — oaths are held regularly, especially after each exam cycle

The key point: you must complete an oath in some form before initial registration. Delaying the oath delays your PRC ID and your ability to legally practice.

---

## Frequently Asked Questions

**Is oath taking required before getting my PRC ID?**
Yes. The professional oath is a legal prerequisite. Your initial registration cannot be completed without recorded oath attendance.

**What should I wear to the PRC oath taking?**
Formal attire — business wear or your profession's recognized formal dress. This applies to online ceremonies too; your camera is on.

**What do I need for online oath taking?**
Any device with internet connection and a camera, your printed Oath Form, a valid ID ready for verification, and your registered name as your display name.

**Do I need to submit proof after an online oath?**
Based on experience, no — attendance is recorded automatically through the session. Keep your Oath Form anyway as part of your registration documents.

**Can my family attend the mass oath taking?**
Policies vary by venue and profession. Many large ceremonies allow guests; check the specific announcement for your batch.

**What happens if I miss my scheduled oath?**
Request a special or individual oath-taking from your Professional Regulatory Board with your reason, join an online ceremony if available, or attend the next scheduled batch.

**Is there a fee for the oath taking?**
The oath registration itself is generally free through LERIS, though professional organizations may collect fees for induction ceremonies held alongside mass oaths. Initial registration fees (₱1,050) are separate.

---

## After the Oath: Your Checklist Continues

The oath is step two of your post-exam journey. See the complete roadmap: [What to Do After Passing the Board Exam Philippines](/blog/after-passing-board-exam-philippines)

And if someone you know is still reviewing for their boards, LisensyaPrep has [free gamified reviewers](/) for nursing, pharmacy, teaching, criminology, and more.
`;

export default function PrcOathTakingGuidePage() {
  return (
    <div className="min-h-screen py-10">
      <Script id="schema-prc-oath-howto" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA_HOWTO) }} />
      <Script id="schema-prc-oath-faq" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA_FAQ) }} />
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

          <article className="lg:col-span-2">
            <nav className="flex items-center gap-2 text-sm mb-6" aria-label="Breadcrumb">
              <Link href="/" className="text-gray-500 hover:text-gray-300 transition-colors">Home</Link>
              <span className="text-gray-700">/</span>
              <Link href="/blog" className="text-gray-500 hover:text-gray-300 transition-colors">Blog</Link>
              <span className="text-gray-700">/</span>
              <span className="text-gray-400 truncate">PRC Oath Taking Guide</span>
            </nav>

            <header className="mb-8">
              <span className="text-xs font-semibold px-3 py-1 rounded-full bg-yellow-400/10 text-yellow-400">PRC Guide</span>
              <h1 className="text-3xl sm:text-4xl font-extrabold text-white mt-4 mb-3 leading-tight">
                PRC Oath Taking Guide 2026: Schedule, Requirements, and Process
              </h1>
              <div className="flex flex-wrap items-center gap-3 text-sm text-gray-500">
                <span>LisensyaPrep Team</span><span>•</span>
                <span>July 10, 2026</span><span>•</span>
                <span>8 min read</span>
              </div>
            </header>

            <div className="prose-content">
              {renderContent(MAIN_CONTENT)}
              <AdPlaceholder slot="banner" className="my-6" />
            </div>

            <div className="mt-10 bg-[#0f1629] border border-white/10 rounded-2xl p-6">
              <h2 className="text-xl font-extrabold text-white mb-4">Related PRC Guides</h2>
              <ul className="space-y-3">
                {RELATED_PRC_ARTICLES.map(({ text, href }) => (
                  <li key={href}>
                    <Link href={href} className="text-yellow-400 hover:text-yellow-300 underline underline-offset-2 text-sm transition-colors">{text}</Link>
                  </li>
                ))}
              </ul>
            </div>

            <div className="mt-8 bg-gradient-to-br from-yellow-900/20 to-yellow-900/10 border border-yellow-500/30 rounded-2xl p-6 text-center">
              <p className="text-yellow-400 font-extrabold text-lg mb-2">Still Reviewing for Your Board Exam?</p>
              <p className="text-gray-400 text-sm mb-4">Free gamified reviewers for PNLE, LET, CLE, and more. No account required.</p>
              <Link href="/" className="inline-block bg-yellow-500 hover:bg-yellow-400 text-black font-bold px-6 py-3 rounded-xl transition-colors">
                Start Practicing at LisensyaPrep
              </Link>
            </div>

            <AdPlaceholder slot="banner" className="mt-8" />
          </article>

          <aside className="space-y-6">
            <div className="bg-[#0f1629] border border-white/10 rounded-2xl p-5">
              <h3 className="text-white font-bold mb-4">PRC Application Guides</h3>
              <div className="space-y-3">
                {RELATED_PRC_ARTICLES.map(({ text, href }) => (
                  <Link key={href} href={href} className="group block">
                    <p className="text-gray-300 text-sm group-hover:text-yellow-400 transition-colors leading-snug">{text}</p>
                  </Link>
                ))}
              </div>
            </div>
            <AdPlaceholder slot="sidebar" />
          </aside>

        </div>
      </div>
    </div>
  );
}
